name: Quick test for PEP517

on:
  push:
    branches: [ master ]
  pull_request:
    branches: '**'

jobs:
  build-n-publish:
    name: Build with PEP517
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install PEP517
        run: >-
          python -m
          pip install
          pep517
          --user
      - name: Test the build backend
        run: >-
          python -m
          pep517.check .
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          pep517.build .
