name: Test with pypa build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: '**'

jobs:
  build-n-publish:
    name: Build with pypa-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          .
